clientapp: main.o client.o functions_for_client.o
	g++    main.o client.o functions_for_client.o -o clientapp

main.o: main.cpp
	g++ -c main.cpp

client.o: client.cpp
	g++ -c client.cpp

functions_for_client.o: functions_for_client.cpp
	g++ -c functions_for_client.cpp
	